<template>
    <div>
        <h1>영화탭 클릭시 이동</h1>
        <div>
            <div>
                <section>
                    <div>
                        <section>
                            <div>
                                <div>
                                    <p>박스오피스 순위</p>
                                </div>
                                <div>
                                    <div>
                                        <div>
                                            <div>
                                                <div>
                                                    <ul>
                                                        <li>영화1</li>
                                                        <li>영화2</li>
                                                        <li>영화3</li>
                                                        <li>영화4</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div>
                                    <p>왓챠 Top10 영화</p>
                                </div>
                                <div>
                                    <div>
                                        <div>
                                            <div>
                                                <div>
                                                    <ul>
                                                        <li>영화1</li>
                                                        <li>영화2</li>
                                                        <li>영화3</li>
                                                        <li>영화4</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div>
                                    <p>넷플릭스 영화 순위</p>
                                </div>
                                <div>
                                    <div>
                                        <div>
                                            <div>
                                                <div>
                                                    <ul>
                                                        <li>영화1</li>
                                                        <li>영화2</li>
                                                        <li>영화3</li>
                                                        <li>영화4</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </section>
            </div>
        </div>
    </div>
</template>
<script setup lang="ts">
import HelloWorld from '../components/HelloWorld.vue';
</script>
<style scoped></style>